### ISSUE TITLE
Aucune lecture sur un prochain titre

### ISSUE THREAD

**Issue by Mylaano** [Mahkalix/Dimension#1]
Hello,

Lorsqu'une écoute est en cours sur un titre et qu'on souhaite écouter un autre, celui-ci ne se lance pas. 
J'étais obligé pour ma part de re-cliquer deux fois dessus pour que ça se lance.

Ce serait sympa de pouvoir corriger ça, good luck!

**Comment by Mahkalix** [comment]
C'est fait :)
